trigger:
- master

pool: self-hosted-ubuntu18.04-scaleset-pool-01

steps:
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'Private AKS Connection Dev'
    namespace: 'default'
    command: 'apply'
    arguments: '-f VotingApp.yaml'
